language: php

services:
        - mysql

matrix:
    include:
        - php: 7.1
        - php: 7.2
        - php: 7.3

install:
    - composer install

script:
    - vendor/bin/phpunit
    - cat $HOME/database_test.log
